deployment:
  name: "app"
  replicas: "3"
  strategy:
    rollingUpdate:
      maxSurge: "1"
      maxUnavailable: "1"
  container:
    name: "app"
    image: "fatihkoc/app:latest"
    imagePullPolicy: "Always"
    port: "3000"
    protocol: "TCP"
    resources:
      requests:
        cpu: "20m"
        memory: "20Mi"
      limits:
        cpu: "200m"
        memory: "200Mi"
    env:
      MYSQL_USERNAME: "MYSQL_USERNAME"
      MYSQL_PASSWORD: "MYSQL_PASSWORD"
      MYSQL_INSTANCE_NAME: "MYSQL_INSTANCE_NAME"
      MYSQL_PORT_3306_TCP_ADDR: "MYSQL_PORT_3306_TCP_ADDR"
      MYSQL_PORT_3306_TCP_PORT: "MYSQL_PORT_3306_TCP_PORT"
    livenessProbe:
      path: "/"
      port: "3000"
      initialDelaySeconds: "30"
      timeoutSeconds: "5"
    readinessProbe:
      path: "/"
      port: "3000"
      initialDelaySeconds: "30"
      timeoutSeconds: "5"

service:
  name: "webserver"
  selector:
    name: "webserver"
  ports:
    protocol: "TCP"
    port: "3000"
    targetPort: "3000"
    type: "NodePort"
    nodePort: "30000"